name: Zerar Planilhas às 17h

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  zerar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Rodar script
        env:
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/zerar-planilhas.js
